
<?php $__env->startSection('title'); ?>
<?php echo app('translator')->get('Add Fund'); ?>
<?php $__env->stopSection(); ?>
<?php $__env->startSection('content'); ?>

<center>
    <div class="">
        <br>
        <br>
        <br>
        <br>
        <?php if($processing == 2): ?>
        <div class="alert bg-white" style="width:500px">

            <br>
            <br>
            <form method="post" action="<?php echo e(route('partner.verify.txn')); ?>" enctype="multipart/form-data">
                <?php echo csrf_field(); ?>
                <div class="">
                    <div class="">
                        <h4>অনুগ্রহ করে ইওয়ালেট অ্যাপ দ্বারা উত্পন্ন লেনদেন নম্বরটি প্রবেশ করুন।</h4>
                        <h4>Please Enter The Transaction Number Generated By The E-Wallet App.</h4>
                        <div class="input-group ">
                            <input type="text" name="txn" class="form-control" placeholder="<?php echo app('translator')->get('Enter Transection No.'); ?>">

                        </div>
                        
                    </div>
                </div>
                <button type="submit" class="btn  btn-primary mt-3"><?php echo app('translator')->get('Submit'); ?></button>
                
            </form>
        </div>
        <?php endif; ?>



        <?php if($processing == 1 ): ?>

        <div class="" style="width:500px" id="processing_div">
            <div class="card">
                <img class="img-fluid" src="<?php echo e(getFile(config('location.public_images.path').'processing.gif')); ?>" />
                <h3>PLEASE WAIT WHILE WE ARE PROCESSING YOUR DEPOSIT.<br> THANK YOU!</h3>
            </div>
        </div>

        <?php endif; ?>

        <div style="width:500px;display:none;" id="complete_div">
            <img class="img-fluid" src="<?php echo e(getFile(config('location.public_images.path').'Complete.gif')); ?>" />
            <h3>TRANSACTION SUCCESSFUL!</h3>
        </div>

        <div style="max-width:500px;display:none;margin:auto" class="alert bg-white" id="pre_complete_div">
            <img class="img-fluid" src="<?php echo e(getFile(config('location.public_images.path').'Complete.gif')); ?>" />
            <div class="col-md-10 mx-auto text-center">
                <h5>Your payment request has been received successfully, and the transaction will be processed within 5 minutes.<br>
                    Thank you!
                </h5>
                <h5>আপনার পেমেন্ট অনুরোধ সফলভাবে গ্রহণ করা হয়েছে এবং লেনদেন ৫ মিনিটের মধ্যে প্রক্রিয়া করা হবে।.<br>
                    ধন্যবাদ!
                </h5>
            </div>
        </div>

    </div>
</center>

<?php $__env->stopSection(); ?>

<?php $__env->startPush('script'); ?>
<script>
    "use strict";
    $(document).ready(function(e) {

        var process_status = "<?php echo e($processing); ?>";

        if (process_status == 1) {
            checkStatus();
        }

        $('#image').change(function() {
            let reader = new FileReader();
            reader.onload = (e) => {
                $('#image_preview_container').attr('src', e.target.result);
            }
            reader.readAsDataURL(this.files[0]);
        });


    });

    $(document).ready(function() {
        $('select').select2({
            selectOnClose: true
        });
    });

    function checkStatus() {
        $.ajax({
            url: "<?php echo e(route('partner.update_fund_order_status.open')); ?>",
            type: 'GET',
            dataType: 'json',
            success: function(response) {
                // console.log(response);
                if (response.status === 'success') {
                    // Handle success condition (e.g., update the UI).

                    $('#processing_div').hide();
                    $('#complete_div').show();
                    $('#pre_complete_div').hide();

                    // Redirect to the fund history page
                    setTimeout(function() {
                        window.location.href = '<?php echo e(route("partner.methods.get", ["username" => $username])); ?>';
                    }, 1500);
                    console.log('Status is success.');
                } else {
                    // If status is not 'success', set a timeout to retry after 10 seconds.
                    $('#processing_div').hide();
                    $('#complete_div').hide();
                    $('#pre_complete_div').show();
                }
            },
            error: function() {
                // Handle AJAX request error if needed.
                console.error('Error occurred during the AJAX request.');
            }
        });
    }
</script>
<?php $__env->stopPush(); ?>

<?php echo $__env->make('partner.layouts.open', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\xampp\htdocs\ecpay\resources\views/partner/payout/paymentProcessingOpen.blade.php ENDPATH**/ ?>