<?php return array (
  'site_title' => 'Your Company Name',
  'base_color' => '#121212',
  'time_zone' => 'Asia/Dhaka',
  'currency' => 'Bangladeshi Taka',
  'currency_symbol' => 'TK',
  'theme' => 'betting',
  'fraction_number' => 0,
  'paginate' => 50,
  'email_verification' => 0,
  'email_notification' => 0,
  'sms_verification' => 0,
  'sms_notification' => 0,
  'push_notification' => 0,
  'error_log' => 1,
  'strong_password' => 0,
  'registration' => 1,
  'address_verification' => 0,
  'identity_verification' => 0,
  'maintenance' => 0,
  'is_active_cron_notification' => 0,
  'sender_email' => 'support@clz.asia',
  'sender_email_name' => 'Online Game Platform',
  'email_configuration' => 
  array (
    'name' => 'smtp',
    'smtp_host' => 'smtp.clz.asia',
    'smtp_port' => '2525',
    'smtp_encryption' => 'ssl',
    'smtp_username' => 'b75b1a5bfa5d58',
    'smtp_password' => 'f89fbe0495a7fc',
  ),
  'win_charge' => '0',
  'refund_charge' => '0',
  'minimum_bet' => '5',
  'deposit_commission' => 1,
  'bet_commission' => 1,
  'bet_win_commission' => 0,
  'theme_mode' => 1,
);